import os
env = Environment ( PATH = os.environ['PATH'] )

coffee_bld = Builder(
    action = 'PATH=$PATH coffee -c -p $SOURCE > $TARGET',
    single_source = True,
    suffix = '.js',
    src_suffix = '.coffee')
env.Append(BUILDERS = {'Coffee' : coffee_bld})

env.Coffee(Glob('*.coffee'))
